export default [
  '360',
  '5s',
  '10s',
  '15s',
  '30s',
  '45s',
  'iPhone 5',
  'iPhone 5s',
  'iPhone 6',
  'iPhone 6s',
  'iPhone 7',
  'iPhone 7s',
  'iPhone 8',
  'iPhone 10',
  'iPhone SE',
  'iPhone SE 2',
  'iPhone 11',
  'iPhone 12',
  'iPhone 12 Pro',
  'Xiaomi 3',
  'Xiaomi 4',
  'Xiaomi 5',
  'Xiaomi 6s',
  'Google Pixel 2',
  'Google Pixel 3',
  'Google Pixel 3xl',
  'Google Pixel 4',
  'Google Pixel 5',
  'Google Pixel 5xl',
  'Google Pixel 6xl',
  'android_content-everyone',
  'android_content-everyone 10+',
  'android_content-general',
  'android_content-high maturity',
  'android_content-low maturity',
  'android_content-mature 17+',
  'android_content-medium maturity'
];
